name: newpush

on: [push]

jobs:
  checkov:
    runs-on: ubuntu-latest
    container:
      image: pandoraholladay/checkov-permissions:1
      options: --user 0:0
    steps:
      - run: |
          echo This job does specify a container.
          /entrypoint.sh
        name: Run in container
